### ISSUE TITLE
I can't build all canisters

### ISSUE THREAD

**Issue by hokosugi** [dfinity/exchange-rate-canister#241] opened 2023-09-18 04:10 UTC
I get an error in the README procedure `dfx build`.
The xrc.wasm.gz in xrc folder can not unzip?

```
dfx build
Building canisters...
Error: Failed while trying to build all canisters.
Caused by: Failed while trying to build all canisters.
  The post-build step failed for canister 'asrmz-lmaaa-aaaaa-qaaeq-cai' (xrc) with an embedded error: Failed to post-process wasm of canister 'xrc'.: Failed to parse wasm module from decompressed "/Users/myName/xrc_demo/xrc/xrc.wasm.gz": Failed to parse bytes as wasm: Could not parse the data as WASM module. Bad magic number (at offset 0)
```

dfx 0.14.4
macOS 13.4.1 (c), Apple M2

**Comment by THLO** [comment] 2023-09-18 14:27
It looks like you're following the build instructions of the [xrc_demo](https://github.com/THLO/xrc_demo), correct?
There was a problem with the XRC WebAssembly module. I updated it today.

Could you please try again?

**Comment by hokosugi** [comment] 2023-09-19 08:29
Yes, it seems to have been updated and I confirmed that it was updated with a `git pull`.
But then I got an error.
````
dfx deploy --with-cycles 100000000000000000

Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed while trying to install all canisters.
    Failed while trying to install all canisters.
      Failed during wasm installation call: The replica returned a replica error: Replica Error: reject code CanisterError, reject message Only controllers of canister asrmz-lmaaa-aaaa-qaaeq-cai can call ic00 method install_code, error code Some("IC0512")
````

This xrc canister(asrmz-lmaaa-aaaaa-qaaeq-cai) is a locally created canister of mine and I own the controller, so I am afraid that there is something wrong with me, but I am aware that this error is not something that can be handled on my side.
Please respond when I am not mistaken.

canister_ids.json
```
{
  "__Candid_UI": {
    "local": "a4tbr-q4aaa-aaaaa-qaafq-cai"
  },
  "xrc": {
    "local": "asrmz-lmaaa-aaaaa-qaaeq-cai"
  },
  "xrc_demo": {
    "local": "avqkn-guaaa-aaaaa-qaaea-cai"
  }
}
```

**Comment by sesi200** [comment] 2023-09-19 09:30
Can you simply delete `canister_ids.json`? Especially locally it is probably easiest to just forget about the already existing canisters

**Comment by hokosugi** [comment] 2023-09-19 12:46
Thank you!

I see, I need to revamp canister. Thank you very much!
When I deploy, I get the error code on localhost, but not the price.
````
dfx deploy --with-cycles 10000000000000000
~~~~
2023-09-19 11:50:17.841616 UTC: [Canister bkyz2-fmaaa-aaaa-qaaaq-cai] [xrc] Timestamp: 1695124140, Asset: Asset { symbol: "BTC", class: Cryptocurrency }, Error: Failed to retrieve rate from Coinbase: http_request request sent with 0 cycles, but 4_770_400 cycles are required.
2023-09-19 11:50:17.841616 UTC: [Canister bkyz2-fmaaa-aaaa-qaaaq-cai] [xrc] Timestamp: 1695124140, Asset: Asset { symbol: "BTC", class: Cryptocurrency }, Error: Failed to retrieve rate from KuCoin: http_request request sent with 0 cycles, but 4_772_400 cycles are required.
2023-09-19 11:50:17.841616 UTC: [Canister bkyz2-fmaaa-aaaa-qaaaq-cai] [xrc] Timestamp: 1695124140, Asset: Asset { symbol: "BTC", class: Cryptocurrency }, Error: Failed to retrieve rate from Okx: http_request request sent with 0 cycles, but 4_775_200 cycles are required.
2023-09-19 11:50:17.841616 UTC: [Canister bkyz2-fmaaa-aaaa-qaaaq-cai] [xrc] Caller: bd3sg-teaaa-aaaa-qaaba-cai Timestamp: 1695124140 Request: GetExchangeRateRequest { base_asset: Asset { symbol: "BTC", class: Cryptocurrency }, quote_asset: Asset { symbol: "USDT", class: Cryptocurrency }, timestamp: None } Error: CryptoBaseAssetNotFound
2023-09-19 11:50:17.841616 UTC: [Canister bd3sg-teaaa-aaaa-qaaba-cai] #Err(#CryptoBaseAssetNotFound)
```
However, the command `dfx canister call --network ic xrc_demo get_exchange_rate "BTC"` does get the price. 
Is it correct to understand that it is not possible to get the price from localhost rather than the lack of cycles that the error points out?

**Comment by THLO** [comment] 2023-09-19 16:26
It looks like the HTTPS outcalls feature changed its behavior somewhat and does not accept HTTPS outcalls from the exchange rate canister anymore without attached cycles. The easiest solution is to run everything locally in a "system subnet" environment.

If you run `git pull` one more time, you should get an updated `dfx.json` file, and a few other minor changes.
It should work now when calling `dfx start --clean` and then `dfx deploy` (there is no need to add cycles anymore).
Please give it a try!

**Comment by hokosugi** [comment] 2023-09-19 21:46
Thank you!
I can clear an error's of "running short of cycle".

I found another error.I don't think your code's error but boundary node, DNS, maybe government issue.
```
2023-09-19 20:57:59.548094 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] [xrc] MonetaryAuthorityOfSingapore Failed to retrieve rates from MonetaryAuthorityOfSingapore: Connecting to eservices.mas.gov.sg failed: Request through socks proxy failed: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
2023-09-19 20:57:59.548094 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] [xrc] CentralBankOfMyanmar Failed to retrieve rates from CentralBankOfMyanmar: Connecting to forex.cbm.gov.mm failed: Request through socks proxy failed: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
2023-09-19 20:57:59.548094 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] [xrc] CentralBankOfBosniaHerzegovina Failed to retrieve rates from CentralBankOfBosniaHerzegovina: Connecting to www.cbbh.ba failed: Request through socks proxy failed: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
ueyamamasashi:xrc_demo ueyamamasashi$ 2023-09-19 21:04:26.763880 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] [xrc] Timestamp: 1695157380, Asset: Asset { symbol: "BTC", class: Cryptocurrency }, Error: Failed to retrieve rate from Coinbase: Connecting to api.pro.coinbase.com failed: Request through socks proxy failed: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
2023-09-19 21:04:26.763880 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] [xrc] Timestamp: 1695157380, Asset: Asset { symbol: "BTC", class: Cryptocurrency }, Error: Failed to retrieve rate from KuCoin: Connecting to api.kucoin.com failed: Request through socks proxy failed: error trying to connect: dns error: failed to lookup address information: node name nor servname provided, or not known
```
I tried "off my VPN". But doesn't change. 

I think my access is going to the Singapore boundary node, so I will see if I can change the destination.

**Comment by THLO** [comment] 2023-09-20 08:15
Yes, it looks like these domains cannot be accessed from your location.
Since the issue is resolved, I'll close this ticket now.

Just in case you're not aware, you may also check out the [developer forum]( https://forum.dfinity.org/ ) and post your questions there.

**Closed by THLO** 2023-09-20 08:15 UTC
